"""PostgreSQL 事件载体(PG2:队列切片)。

**为什么先迁队列而不是整库**:队列是最适合当试点的切片——接口早就抽好
(`EventBus` Protocol),语义契约逐条写清,而且它的正确性有全项目最强的测试覆盖
(幂等认领、优先级、三态、扇出、滞留回收)。整库迁移(PG3)是 245 处占位符 + 13 个
写 SQL 的模块,拿它当第一步无法二分定位问题。

**SQLite 到底卡住了什么**:`Database.claim_events` 是"先 SELECT 候选 id,再逐行带
`status='pending'` 条件 UPDATE"。单实例下完全正确(条件更新保证同一行只会被一个
worker 改到),但多实例下两个 worker 会 SELECT 到**同一批 id**,然后互相抢——抢输的
那方 rowcount=0、白跑一圈。规模越大空转越多,而且这件事**不会报错**,只表现为
"worker 明明在跑,吞吐却上不去"。

PG 用一条语句解决:

    UPDATE agent_events SET status='processing', consumed_at=now()
    WHERE id IN (SELECT id FROM agent_events
                 WHERE target_agent=%s AND status='pending'
                 ORDER BY priority DESC, id ASC
                 LIMIT %s
                 FOR UPDATE SKIP LOCKED)
    RETURNING *;

`FOR UPDATE SKIP LOCKED` 让并发 worker **各取各的、互不阻塞**——这正是 SQLite 做不到、
而 Kafka 虽然能并发消费却给不了优先级的那个位置。

---

**本模块刻意只做队列这一张表。** 业务数据仍在 SQLite,所以现阶段
`publish` 与业务写**不在同一事务**里。这是一个**已知的、暂时的**代价,不是遗漏:

- 队列先迁是为了验证 `FOR UPDATE SKIP LOCKED` 这条路子和全套语义契约;
- 长期方向是 PG3 把业务库整体迁过来,`agent_events` 只是其中一张表,
  `publish` 与业务写自然回到同一事务(见 `docs/superpowers/plans/2026-08-08-postgres-migration.md`
  第一节:只迁队列是本末倒置);
- 因此**默认不启用**(`collab_bus_backend=sqlite`),开关打开才走这里。

时间戳用 PG 的 `now()`,不从 Python 传:多实例下各机器时钟不一致,而
`reclaim_stale` 要靠"认领时刻 + 阈值"判滞留,时间基准必须只有一个。这与 SQLite 版
从 Python 传 `_now()` 是**刻意的不同**——SQLite 是单机,PG 是多机。
"""

from __future__ import annotations

import json
import logging
from typing import Optional

logger = logging.getLogger(__name__)

#: 建表语句。与 SQLite 版**列名、语义完全一致**,只换掉方言部分:
#: AUTOINCREMENT → GENERATED AS IDENTITY,TEXT 时间戳 → timestamptz。
#: 刻意不趁机改表结构(见方案 Global Constraints 4):迁移与建模同时做,
#: 出问题时无法二分定位。
SCHEMA = """
CREATE TABLE IF NOT EXISTS agent_events (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type     text NOT NULL,
    payload        text,
    source_agent   text,
    target_agent   text NOT NULL,
    correlation_id text,
    status         text NOT NULL DEFAULT 'pending',
    priority       integer NOT NULL DEFAULT 0,
    created_at     timestamptz NOT NULL DEFAULT now(),
    consumed_at    timestamptz
);
-- 认领走的就是这个复合序:target + status 过滤,再按 priority DESC, id ASC 排序
CREATE INDEX IF NOT EXISTS idx_agent_events_target
    ON agent_events (target_agent, status, priority DESC, id);
CREATE INDEX IF NOT EXISTS idx_agent_events_corr
    ON agent_events (correlation_id, id);
"""


def _row_to_event(row: dict) -> dict:
    """把一行转成上层认的形状。

    两处必须与 SQLite 版对齐,否则上层会静默出错:

    1. `payload` 反序列化成 dict;**坏 JSON 跳过整行**(与 `claim_events` 同口径)
       ——单条脏数据不该拖垮整个消费循环。这里返回 None 表示"这行丢掉"。
    2. 时间戳转成 `YYYY-MM-DD HH:MM:SS` 字符串。PG 给的是 datetime 对象,而前端
       与 `list_event_chains` 的调用方都按字符串处理;在载体层归一化,不让
       "换了后端所以时间字段类型变了"这件事漏到上层。
    """
    item = dict(row)
    raw = item.get("payload")
    if raw is None or raw == "":
        item["payload"] = {}
    else:
        try:
            item["payload"] = json.loads(raw)
        except (json.JSONDecodeError, TypeError):
            logger.warning("agent_events 行 payload 不是合法 JSON,跳过 id=%s",
                           item.get("id"))
            return None
    for col in ("created_at", "consumed_at"):
        val = item.get(col)
        if val is not None and not isinstance(val, str):
            item[col] = val.strftime("%Y-%m-%d %H:%M:%S")
    return item


class PostgresEventBus:
    """PG 载体。构造时接连接串,便于测试注入独立库。

    每次操作现开连接(用 psycopg 的连接池语义由调用方决定):这一层刻意保持薄,
    与 `SqliteEventBus` 一样"载体层多一分自己的判断,换载体时就多一分要重新
    验证的东西"。
    """

    def __init__(self, dsn: str, autocommit: bool = True):
        self._dsn = dsn
        self._autocommit = autocommit

    # ---------- 连接 ----------

    def _connect(self):
        import psycopg
        from psycopg.rows import dict_row

        return psycopg.connect(self._dsn, autocommit=self._autocommit,
                               row_factory=dict_row)

    def init_schema(self) -> None:
        with self._connect() as conn:
            conn.execute(SCHEMA)

    # ---------- 契约实现 ----------

    def publish(self, event_type: str, payload: dict, source: str, target: str,
                correlation_id: str, priority: int = 0) -> int:
        with self._connect() as conn:
            row = conn.execute(
                "INSERT INTO agent_events (event_type, payload, source_agent, "
                "target_agent, correlation_id, status, priority) "
                "VALUES (%s, %s, %s, %s, %s, 'pending', %s) RETURNING id",
                (event_type, json.dumps(payload or {}, ensure_ascii=False),
                 source, target, correlation_id, int(priority))).fetchone()
            return int(row["id"])

    def claim(self, target: str, limit: int = 20) -> list[dict]:
        """原子认领。**一条语句**完成 SELECT + UPDATE,多实例安全。

        `FOR UPDATE SKIP LOCKED` 是这里的全部要点:并发 worker 各取各的、互不阻塞,
        而 SQLite 版("先 SELECT 再逐行条件 UPDATE")在多实例下会 SELECT 到同一批 id
        再互相抢,抢输的白跑一圈——不报错,只表现为吞吐上不去。

        排序**必须**是 `priority DESC, id ASC`:同优先级严格 FIFO 这一点不能丢,
        它是"为什么这条比那条晚处理"可解释性的唯一来源。
        """
        with self._connect() as conn:
            rows = conn.execute(
                "UPDATE agent_events SET status = 'processing', consumed_at = now() "
                "WHERE id IN ("
                "    SELECT id FROM agent_events "
                "    WHERE target_agent = %s AND status = 'pending' "
                "    ORDER BY priority DESC, id ASC "
                "    LIMIT %s "
                "    FOR UPDATE SKIP LOCKED"
                ") RETURNING *", (target, int(limit))).fetchall()
        # RETURNING 的顺序不保证,而上层依赖"按优先级/FIFO 交给我"——在这里排回去。
        # 不能指望调用方自己排:SQLite 版是有序的,换后端后如果这里无序,
        # 上层会在完全不相关的地方表现出乱序。
        out = [e for e in (_row_to_event(r) for r in rows) if e is not None]
        out.sort(key=lambda e: (-int(e.get("priority") or 0), int(e["id"])))
        return out

    def finish(self, event_id: int, status: str) -> bool:
        """终结一条事件。**只对仍是 processing 的行生效**(条件更新)。

        这个条件是幂等的根基:重复调用、两个 worker 同时收尾,只有第一次真的改到。
        """
        with self._connect() as conn:
            cur = conn.execute(
                "UPDATE agent_events SET status = %s "
                "WHERE id = %s AND status = 'processing'", (status, int(event_id)))
            return cur.rowcount > 0

    def reclaim_stale(self, older_than_seconds: int = 300) -> int:
        """把滞留在 processing 超阈值的行放回 pending(救"认领后崩在半路")。

        阈值比较用**数据库的 now()**,不用 Python 的:多实例下各机器时钟不一致,
        而这里判的正是"距离认领时刻过了多久"。

        `consumed_at` 一并清空,否则下一轮 reclaim 会看到一条"很久以前认领的"
        pending 行,再次把它当滞留处理(与 SQLite 版同一条注释)。
        """
        with self._connect() as conn:
            cur = conn.execute(
                "UPDATE agent_events SET status = 'pending', consumed_at = NULL "
                "WHERE status = 'processing' AND consumed_at IS NOT NULL "
                "AND consumed_at <= now() - make_interval(secs => %s)",
                (float(older_than_seconds),))
            return cur.rowcount

    def timeline(self, correlation_id: Optional[str] = None,
                 limit: int = 100) -> list[dict]:
        sql = "SELECT * FROM agent_events"
        params: list = []
        if correlation_id:
            sql += " WHERE correlation_id = %s"
            params.append(correlation_id)
        sql += " ORDER BY id DESC LIMIT %s"
        params.append(int(limit))
        with self._connect() as conn:
            rows = conn.execute(sql, tuple(params)).fetchall()
        return [e for e in (_row_to_event(r) for r in rows) if e is not None]

    def failed(self, limit: int = 50) -> list[dict]:
        with self._connect() as conn:
            rows = conn.execute(
                "SELECT id, event_type, source_agent, target_agent, correlation_id, "
                "       payload, created_at, consumed_at "
                "FROM agent_events WHERE status = 'failed' "
                "ORDER BY id DESC LIMIT %s", (int(limit),)).fetchall()
        return [e for e in (_row_to_event(r) for r in rows) if e is not None]

    def failed_count(self) -> int:
        with self._connect() as conn:
            row = conn.execute(
                "SELECT COUNT(*) AS c FROM agent_events WHERE status = 'failed'"
            ).fetchone()
            return int(row["c"])

    def retry(self, event_id: int) -> bool:
        """把一条失败事件放回待处理队列。

        条件更新(`status='failed'`):连点两次、两个运营同时点,只有第一次真的改到,
        第二次拿到 False 而不是把一条已经在跑的事件又打回队列。
        `consumed_at` 清空,理由同 `reclaim_stale`。
        """
        with self._connect() as conn:
            cur = conn.execute(
                "UPDATE agent_events SET status = 'pending', consumed_at = NULL "
                "WHERE id = %s AND status = 'failed'", (int(event_id),))
            return cur.rowcount > 0
